docker-java version updated to 3.1.5
eclipse-iofog/Agent pull request #294
Opened 2019-12-09 00:29 UTC by NehaNaithani

2020-01-21 18:12 UTC, baghbidi requested changes

2020-01-21 18:12 UTC, baghbidi commented on iofog-agent-client/src/main/java/org/eclipse/iofog/Client.java
> +                "                 -dt <#percentage>          Set the available disk threshold\\n" +
Extra spaces

2020-01-21 18:12 UTC, baghbidi commented on iofog-agent-daemon/src/main/java/org/eclipse/iofog/command_line/CommandLineAction.java
> +			"                 -dt <#percentage>          Set the available disk threshold\\n" +
Extra spaces

2020-01-21 18:12 UTC, baghbidi commented on iofog-agent-daemon/src/main/java/org/eclipse/iofog/command_line/CommandLineConfigParam.java
> +    DOCKER_PRUNING_FREQUENCY ("2000", "pf", "docker_pruning_freq", "dockerPruningFrequency"),
The value should be in seconds, to be consistent with other config values like checkStatusFrequency,...

2020-01-21 18:12 UTC, baghbidi commented on iofog-agent-daemon/src/main/java/org/eclipse/iofog/field_agent/FieldAgent.java
> +                if (changes.containsKey("deleteNode") && (changes.getBoolean("deleteNode") && !initialization)) {
You could use defaultValue here IMO:
```
if (changes.getBoolean("deleteNode", false) && !initialization)
```

2020-01-21 19:38 UTC, NehaNaithani commented on iofog-agent-daemon/src/main/java/org/eclipse/iofog/field_agent/FieldAgent.java
> +                if (changes.containsKey("deleteNode") && (changes.getBoolean("deleteNode") && !initialization)) {
updated

2020-01-21 19:38 UTC, NehaNaithani commented on iofog-agent-daemon/src/main/java/org/eclipse/iofog/command_line/CommandLineConfigParam.java
> +    DOCKER_PRUNING_FREQUENCY ("2000", "pf", "docker_pruning_freq", "dockerPruningFrequency"),
updated to 60

2020-01-21 19:39 UTC, NehaNaithani commented on iofog-agent-daemon/src/main/java/org/eclipse/iofog/command_line/CommandLineAction.java
> +			"                 -dt <#percentage>          Set the available disk threshold\\n" +
removed

2020-01-21 19:39 UTC, NehaNaithani commented on iofog-agent-client/src/main/java/org/eclipse/iofog/Client.java
> +                "                 -dt <#percentage>          Set the available disk threshold\\n" +
removed

2020-01-22 19:43 UTC, baghbidi approved these changes

2020-01-22 19:54 UTC, merged